'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.7905
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SRT_Lab.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Entypo_2795_2__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_2795(2)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Entypo_d83d_2__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_d83d(2)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Entypo_e744_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_e744(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Entypo_e75d_1__32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_e75d(1)_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Entypo_e75e_0__32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_e75e(0)_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Entypo_e778_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Entypo_e778(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f00d_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f00d(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f00e_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f00e(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f010_1__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f010(1)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f040_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f040(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f047_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f047(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f0b2_1__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f0b2(1)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FontAwesome_f15b_0__64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FontAwesome_f15b(0)_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
